### PR TITLE
feat: support schnorr_1 for zilliqa

### PR DESCRIPTION
**Pull request by renlulu**
### Motivation
This PR is to support Zilliqa schnorr signature algorithm.

### Solution
Add `Sign` and `Verify` functions for `secp256k1` by using zilliqa golang sdk.

### CODE REVIEW

**Review by patrick-ogrady — DISMISSED** [review]
🚀

**Comment by patrick-ogrady** [comment]
@renlulu it won't let me merge this until you sign your commits 😢 
image

**Comment by renlulu** [comment]
@patrick-ogrady Oh ok! I will redo this PR.

**Comment by patrick-ogrady** [comment]
Looks good otherwise!

**Comment by renlulu** [comment]
@patrick-ogrady I signed it. Hope you don't mind my force push here, or I can do a fresh PR.

**Review by patrick-ogrady — APPROVED** [review]

**Comment by patrick-ogrady** [comment]
force push is fine!

**Pull request merged**
