### PR TITLE
Make middlewares optional

### LINKED ISSUE #59: Make the Logger an optional middleware in routers
**Is your feature request related to a problem? Please describe.**
Using the current router mux exported by the server package results in endpoints always logging accesses in a specific format. When running a Rosetta server implementation backed by some other pre-existing node server that logs in a different format, logs become slightly harder to read.

Additionally, we might want to offer different forms of logging or offer the option to disable logging altogether to users. 

**Describe the solution you'd like**
Make middlewares (including the currently existing Logger) configurable when calling `server.NewRouter`.

**Describe alternatives you've considered**
Another alternative would be disabling logging altogether in the library and having that be a responsibility of users.

### PR DESCRIPTION
**Pull request by matheusd**
This makes the middlewares offered by the server package optional. This
allows full customization by implementations.

Fixes #59

### CODE REVIEW

**Comment by patrick-ogrady** [comment]
@matheusd Just an FYI that it won't let me review this until you sign your commit.

**Comment by patrick-ogrady** [comment]
Example logs look great:

```
2020/07/24 13:58:36 Listening on port 8080
2020/07/24 13:58:51 POST /network/list 189.853µs
2020/07/24 13:58:51 POST /network/status 250.172µs
2020/07/24 13:58:51 POST /network/options 110.503µs
2020/07/24 13:58:51 POST /block 294.214µs
2020/07/24 13:58:51 POST /block/transaction 84.845µs
2020/07/24 13:58:51 POST /block 100.8µs
2020/07/24 13:58:51 POST /block 97.317µs
2020/07/24 13:58:51 POST /block 133.419µs
2020/07/24 13:58:51 POST /block 251.101µs
2020/07/24 13:58:51 POST /block 149.209µs
2020/07/24 13:58:51 POST /block 129.884µs
2020/07/24 13:58:51 POST /block 446.035µs
2020/07/24 13:58:51 POST /block 451.176µs
2020/07/24 13:58:51 POST /block 314.461µs
2020/07/24 13:58:51 POST /block 222.318µs
2020/07/24 13:58:51 POST /block 220.745µs
```

**Comment by patrick-ogrady** [comment]
Awesome work @matheusd 🎉

**Comment by matheusd** [comment]
Should've mentioned in the original msg, but here's something that can produce customizable logging with slightly more info (status code, total bytes sent): https://github.com/matheusd/middlelogger/

**Pull request merged**
